# Generated by Django 3.2.2 on 2021-10-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_no',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
