# Generated by Django 3.2.2 on 2021-10-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_no',
            field=models.CharField(max_length=14),
        ),
    ]
