# Generated by Django 3.2.2 on 2021-09-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='user', max_length=50, unique=True),
        ),
    ]
