# Generated by Django 3.1 on 2021-06-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'CartItems', 'verbose_name_plural': 'CartItems'},
        ),
    ]
